// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/listBrands.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.77.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find(
          (v) => typeof v === "string" && v.trim().startsWith("sb_publishable_")
        )?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error(
    "SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required"
  );
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/listBrands.ts
var listBrands_default = defineTool({
  name: "list_brands",
  title: "List brands",
  description: "List brands the signed-in user can access, with optional name search.",
  inputSchema: {
    search: z.string().trim().optional().describe("Filter brands by name."),
    limit: z.number().int().optional().describe("Max rows to return (default 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("brands").select("id, name, website, markets, categories, created_at").order("name").limit(Math.min(Math.max(limit ?? 50, 1), 200));
    if (search) query = query.ilike("name", `%${search}%`);
    const { data, error } = await query;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { brands: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/listCampaigns.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^3.25.76";
var listCampaigns_default = defineTool2({
  name: "list_campaigns",
  title: "List campaigns",
  description: "List campaigns visible to the signed-in user, optionally filtered by brand, status, or name.",
  inputSchema: {
    brandId: z2.string().uuid().optional().describe("Only campaigns for this brand id."),
    status: z2.string().trim().optional().describe("Campaign status filter, e.g. active."),
    search: z2.string().trim().optional().describe("Filter by campaign name."),
    limit: z2.number().int().optional().describe("Max rows to return (default 25).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ brandId, status, search, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("campaigns").select(
      "id, name, status, funnel_type, start_date, end_date, cost_idr, primary_kpi, kpi_target, brand:brands(id, name), channel:channels(id, name)"
    ).order("created_at", { ascending: false }).limit(Math.min(Math.max(limit ?? 25, 1), 100));
    if (brandId) query = query.eq("brand_id", brandId);
    if (status) query = query.eq("status", status);
    if (search) query = query.ilike("name", `%${search}%`);
    const { data, error } = await query;
    if (error) {
      return { content: [{ type: "text", text: error.message }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { campaigns: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/getCampaignPerformance.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^3.25.76";
var getCampaignPerformance_default = defineTool3({
  name: "get_campaign_performance",
  title: "Get campaign performance",
  description: "Return a campaign's details plus aggregated performance metrics (impressions, reach, clicks, engagements, spend) over an optional date range.",
  inputSchema: {
    campaignId: z3.string().uuid().describe("Campaign id."),
    startDate: z3.string().trim().optional().describe("Inclusive start date, YYYY-MM-DD."),
    endDate: z3.string().trim().optional().describe("Inclusive end date, YYYY-MM-DD.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ campaignId, startDate, endDate }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data: campaign, error: campaignError } = await supabase.from("campaigns").select(
      "id, name, status, funnel_type, start_date, end_date, cost_idr, primary_kpi, kpi_target, brand:brands(id, name)"
    ).eq("id", campaignId).maybeSingle();
    if (campaignError) {
      return { content: [{ type: "text", text: campaignError.message }], isError: true };
    }
    if (!campaign) {
      return {
        content: [{ type: "text", text: "Campaign not found or not accessible." }],
        isError: true
      };
    }
    let metricsQuery = supabase.from("metrics").select("date, impressions, reach, clicks, engagements, video_views, spend").eq("campaign_id", campaignId).order("date");
    if (startDate) metricsQuery = metricsQuery.gte("date", startDate);
    if (endDate) metricsQuery = metricsQuery.lte("date", endDate);
    const { data: metrics, error: metricsError } = await metricsQuery;
    if (metricsError) {
      return { content: [{ type: "text", text: metricsError.message }], isError: true };
    }
    const rows = metrics ?? [];
    const sum = (key) => rows.reduce((total, row) => total + (Number(row[key]) || 0), 0);
    const totals = {
      days: rows.length,
      impressions: sum("impressions"),
      reach: sum("reach"),
      clicks: sum("clicks"),
      engagements: sum("engagements"),
      videoViews: sum("video_views"),
      spend: sum("spend")
    };
    const ctr = totals.impressions ? totals.clicks / totals.impressions : 0;
    const summary = { ...totals, ctr };
    return {
      content: [
        { type: "text", text: JSON.stringify({ campaign, summary }, null, 2) }
      ],
      structuredContent: { campaign, summary, metrics: rows }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "kqenlckrxqqavpiytjpm";
var mcp_default = defineMcp({
  name: "was-media-hub",
  title: "WAS Media Hub",
  version: "0.1.0",
  instructions: "Tools for WAS Media Hub, a media campaign performance platform. Use `list_brands` to find brands, `list_campaigns` to browse campaigns (optionally by brand or status), and `get_campaign_performance` for a campaign's details plus aggregated metrics. All tools act as the signed-in user and respect their access permissions.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [listBrands_default, listCampaigns_default, getCampaignPerformance_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
